-- testing data
-- Security Questions
INSERT INTO SecurityQuestion (question) VALUES
('What is your mothers maiden name?'),
('What was the name of your first pet?'),
('What is your favorite book?'),
('What city were you born in?'),
('What is your childhood nickname?');

-- Users
INSERT INTO User (username, password_hash, real_name, date_of_birth, description, avatar_url, is_admin, is_active, security_question_id, security_answer, updated_at) VALUES
('anpanman', 'hashed_pw_1', 'Anpan Man', '1990-01-01', 'The hero of justice!', 'temp/tmpImages/anpanman.webp', 1, 1, 1, 'answer1', CURRENT_TIMESTAMP),
('baikinman', 'hashed_pw_2', 'Baikin Man', '1991-02-02', 'The mischievous germ.', 'temp/tmpImages/baikinman.webp', 0, 1, 2, 'answer2', CURRENT_TIMESTAMP),
('dokinchan', 'hashed_pw_3', 'Dokin Chan', '1992-03-03', 'Baikinman’s partner.', 'temp/tmpImages/dokinchan.webp', 0, 1, 3, 'answer3', CURRENT_TIMESTAMP),
('shokupanman', 'hashed_pw_4', 'Shokupan Man', '1993-04-04', 'The bread-headed hero.', 'temp/tmpImages/shokupanman.webp', 0, 1, 4, 'answer4', CURRENT_TIMESTAMP),
('currypanman', 'hashed_pw_5', 'Currypan Man', '1994-05-05', 'Spicy and strong!', 'temp/tmpImages/currypanman.webp', 0, 1, 5, 'answer5', CURRENT_TIMESTAMP),
('melonpanna', 'hashed_pw_6', 'Melon Panna', '1995-06-06', 'Sweet and gentle.', 'temp/tmpImages/melonpanna.jpg', 0, 1, 1, 'answer6', CURRENT_TIMESTAMP),
('cheese', 'hashed_pw_7', 'Cheese', '1996-07-07', 'Anpanman’s loyal dog.', 'temp/tmpImages/cheese.jpg', 0, 1, 2, 'answer7', CURRENT_TIMESTAMP),
('horrorman', 'hashed_pw_8', 'Horror Man', '1997-08-08', 'A skeleton with a heart.', 'temp/tmpImages/horrorman.jpg', 0, 1, 3, 'answer8', CURRENT_TIMESTAMP),
('kabao', 'hashed_pw_9', 'Kabao', '1998-09-09', 'The friendly hippo.', 'temp/tmpImages/kabao.jpg', 0, 1, 4, 'answer9', CURRENT_TIMESTAMP),
('creampanda', 'hashed_pw_10', 'Cream Panda', '1999-10-10', 'The youngest hero.', 'temp/tmpImages/creampanda.jpg', 0, 1, 5, 'answer10', CURRENT_TIMESTAMP),
('rollpanna', 'hashed_pw_11', 'Roll Panna', '2000-11-11', 'Melonpanna’s sister.', 'temp/tmpImages/rollpanna.jpg', 0, 1, 1, 'answer11', CURRENT_TIMESTAMP),
('omusubiman', 'hashed_pw_12', 'Omusubi Man', '1989-12-12', 'The rice ball hero.', 'temp/tmpImages/omusubiman.jpg', 0, 1, 2, 'answer12', CURRENT_TIMESTAMP),
('kamameshidon', 'hashed_pw_13', 'Kamameshidon', '1988-01-13', 'The pot rice hero.', 'temp/tmpImages/kamameshidon.webp', 0, 1, 3, 'answer13', CURRENT_TIMESTAMP),
('butterko', 'hashed_pw_14', 'Butterko', '1987-02-14', 'The butter fairy.', 'temp/tmpImages/butterko.webp', 0, 1, 4, 'answer14', CURRENT_TIMESTAMP),
('jamojisan', 'hashed_pw_15', 'Jam Ojisan', '1986-03-15', 'The baker and inventor.', 'temp/tmpImages/jamojisan.webp', 0, 1, 5, 'answer15', CURRENT_TIMESTAMP);

-- Articles (2 per user, 30 total)
INSERT INTO Article (author_id, title, content, header_image_url, is_active) VALUES
(1, 'Anpanman’s First Adventure', 'Anpanman saves the day!', 'temp/tmpImages/article1.jpg', 1),
(1, 'Anpanman vs Baikinman', 'A classic showdown.', 'temp/tmpImages/article2.jpg', 1),
(2, 'Baikinman’s Mischief', 'Trouble in the town!', 'temp/tmpImages/article3.jpg', 1),
(2, 'Baikinman Builds a Robot', 'A new invention appears.', 'temp/tmpImages/article4.jpg', 1),
(3, 'Dokinchan’s Dream', 'A wish upon a star.', 'temp/tmpImages/article5.jpg', 1),
(3, 'Dokinchan and Melonpanna', 'A sweet friendship.', 'temp/tmpImages/article6.jpg', 1),
(4, 'Shokupanman’s Bakery', 'Fresh bread every morning.', 'temp/tmpImages/article7.png', 1),
(4, 'Shokupanman’s Rescue', 'Helping a friend in need.', 'temp/tmpImages/article8.png', 1),
(5, 'Currypanman’s Spice', 'A spicy adventure!', 'temp/tmpImages/article9.webp', 1),
(5, 'Currypanman’s Cooking Tips', 'How to make the best curry.', 'temp/tmpImages/article10.png', 1),
(6, 'Melonpanna’s Song', 'Singing to cheer everyone up.', 'temp/tmpImages/article11.jpg', 1),
(6, 'Melonpanna’s Picnic', 'A day in the park.', 'temp/tmpImages/article12.jpg', 1),
(7, 'Cheese’s Loyalty', 'A dog’s devotion.', 'temp/tmpImages/article13.webp', 1),
(7, 'Cheese’s New Friend', 'Meeting a new puppy.', 'temp/tmpImages/article14.webp', 1),
(8, 'Horrorman’s Prank', 'A spooky surprise.', 'temp/tmpImages/article15.jpg', 1),
(8, 'Horrorman’s Apology', 'Making amends.', 'temp/tmpImages/article16.jpg', 1),
(9, 'Kabao’s Big Splash', 'Fun at the lake.', 'temp/tmpImages/article17.webp', 1),
(9, 'Kabao’s Picnic', 'A feast for friends.', 'temp/tmpImages/article18.jpg', 1),
(10, 'Cream Panda’s First Mission', 'Learning to be a hero.', 'temp/tmpImages/article19.jpg', 1),
(10, 'Cream Panda’s Mistake', 'Learning from errors.', 'temp/tmpImages/article20.jpg', 1),
(11, 'Rollpanna’s Dilemma', 'Good vs. evil.', 'temp/tmpImages/article21.png', 1),
(11, 'Rollpanna’s Help', 'Helping Melonpanna.', 'temp/tmpImages/article22.jpg', 1),
(12, 'Omusubi Man’s Journey', 'Traveling the world.', 'temp/tmpImages/article23.jpg', 1),
(12, 'Omusubi Man’s Recipe', 'The secret to great rice balls.', 'temp/tmpImages/article24.jpg', 1),
(13, 'Kamameshidon’s Feast', 'A big dinner party.', 'temp/tmpImages/article25.jpg', 1),
(13, 'Kamameshidon’s Adventure', 'Lost in the woods.', 'temp/tmpImages/article26.webp', 1),
(14, 'Butterko’s Magic', 'A touch of butter makes it better.', 'temp/tmpImages/article27.webp', 1),
(14, 'Butterko’s Gift', 'A present for a friend.', 'temp/tmpImages/article28.png', 1),
(15, 'Jam Ojisan’s Bakery', 'Baking with love.', 'temp/tmpImages/article29.webp', 1),
(15, 'Jam Ojisan’s Invention', 'A new gadget for the kitchen.', 'temp/tmpImages/article30.webp', 1);

-- Images (1-4 per article)
INSERT INTO Image (article_id, url) VALUES
(1, 'temp/tmpImages/article1.jpg'),
(2, 'temp/tmpImages/article2.jpg'),
(3, 'temp/tmpImages/article3.jpg'),
(4, 'temp/tmpImages/article4.jpg'),
(4, 'temp/tmpImages/article4b.jpg'),
(4, 'temp/tmpImages/article4c.jpg'),
(5, 'temp/tmpImages/article5.jpg'),
(6, 'temp/tmpImages/article6.jpg'),
(7, 'temp/tmpImages/article7.png'),
(7, 'temp/tmpImages/article7b.webp'),
(8, 'temp/tmpImages/article8.png'),
(9, 'temp/tmpImages/article9.webp'),
(10, 'temp/tmpImages/article10.png'),
(11, 'temp/tmpImages/article11.jpg'),
(12, 'temp/tmpImages/article12.jpg'),
(13, 'temp/tmpImages/article13.webp'),
(13, 'temp/tmpImages/article13b.avif'),
(13, 'temp/tmpImages/article13c.jpg'),
(13, 'temp/tmpImages/article13d.webp'),
(14, 'temp/tmpImages/article14.webp'),
(15, 'temp/tmpImages/article15.jpg'),
(16, 'temp/tmpImages/article16.jpg'),
(17, 'temp/tmpImages/article17.webp'),
(18, 'temp/tmpImages/article18.jpg'),
(19, 'temp/tmpImages/article19.jpg'),
(20, 'temp/tmpImages/article20.jpg'),
(21, 'temp/tmpImages/article21.png'),
(21, 'temp/tmpImages/article21b.png'),
(22, 'temp/tmpImages/article22.jpg'),
(23, 'temp/tmpImages/article23.jpg'),
(24, 'temp/tmpImages/article24.jpg'),
(25, 'temp/tmpImages/article25.jpg'),
(25, 'temp/tmpImages/article25b.webp'),
(26, 'temp/tmpImages/article26.webp'),
(27, 'temp/tmpImages/article27.webp'),
(28, 'temp/tmpImages/article28.png'),
(28, 'temp/tmpImages/article28b.jpg'),
(28, 'temp/tmpImages/article28c.jpg'),
(29, 'temp/tmpImages/article29.webp'),
(30, 'temp/tmpImages/article30.webp');

-- Comments (2-4 per article, some nested)
INSERT INTO Comment (article_id, author_id, parent_comment_id, content, is_active) VALUES
(1, 2, NULL, 'Great adventure!', 1),
(1, 3, 1, 'I agree! Anpanman is the best.', 1),
(2, 4, NULL, 'Classic rivalry.', 1),
(2, 1, 3, 'Thanks for reading!', 1),
(3, 5, NULL, 'Baikinman is so funny.', 1),
(4, 6, NULL, 'Robots are cool!', 1),
(5, 7, NULL, 'Dokinchan’s dream is sweet.', 1),
(6, 8, NULL, 'Melonpanna is so kind.', 1),
(7, 9, NULL, 'Fresh bread is the best.', 1),
(8, 10, NULL, 'Shokupanman to the rescue!', 1),
(9, 11, NULL, 'Spicy adventure!', 1),
(10, 12, NULL, 'I love curry tips.', 1),
(11, 13, NULL, 'Beautiful song!', 1),
(12, 14, NULL, 'Picnic time!', 1),
(13, 15, NULL, 'Cheese is loyal.', 1),
(14, 1, NULL, 'New puppy is cute.', 1),
(15, 2, NULL, 'Spooky prank!', 1),
(16, 3, NULL, 'Apology accepted.', 1),
(17, 4, NULL, 'Big splash!', 1),
(18, 5, NULL, 'Feast for friends.', 1),
(19, 6, NULL, 'First mission success!', 1),
(20, 7, NULL, 'Mistakes happen.', 1),
(21, 8, NULL, 'Dilemma resolved.', 1),
(22, 9, NULL, 'Helping is good.', 1),
(23, 10, NULL, 'Journey is fun.', 1),
(24, 11, NULL, 'Great recipe!', 1),
(25, 12, NULL, 'Dinner party was awesome.', 1),
(26, 13, NULL, 'Adventure time!', 1),
(27, 14, NULL, 'Magic touch!', 1),
(28, 15, NULL, 'Lovely gift.', 1),
(29, 1, NULL, 'Baking with love.', 1),
(30, 2, NULL, 'New invention rocks!', 1);

-- Likes (randomly distributed, each article gets 2-5 likes, each comment gets 1-2 likes)
INSERT INTO Like (article_id, user_id, comment_id, is_active) VALUES
(1, 2, NULL, 1), (1, 3, NULL, 1), (1, 4, NULL, 1),
(2, 1, NULL, 1), (2, 5, NULL, 1),
(3, 6, NULL, 1), (3, 7, NULL, 1),
(4, 8, NULL, 1), (4, 9, NULL, 1),
(5, 10, NULL, 1), (5, 11, NULL, 1),
(6, 12, NULL, 1), (6, 13, NULL, 1),
(7, 14, NULL, 1), (7, 15, NULL, 1),
(8, 1, NULL, 1), (8, 2, NULL, 1),
(9, 3, NULL, 1), (9, 4, NULL, 1),
(10, 5, NULL, 1), (10, 6, NULL, 1),
(11, 7, NULL, 1), (11, 8, NULL, 1),
(12, 9, NULL, 1), (12, 10, NULL, 1),
(13, 11, NULL, 1), (13, 12, NULL, 1),
(14, 13, NULL, 1), (14, 14, NULL, 1),
(15, 15, NULL, 1), (15, 1, NULL, 1),

-- Likes for comments
(NULL, 2, 1, 1), (NULL, 3, 2, 1), (NULL, 4, 3, 1), (NULL, 5, 4, 1), (NULL, 6, 5, 1),
(NULL, 7, 6, 1), (NULL, 8, 7, 1), (NULL, 9, 8, 1), (NULL, 10, 9, 1), (NULL, 11, 10, 1);

-- Notifications for article likes (recipient_id = article author, actor_id = liker, article_id = liked article)
INSERT INTO Notification (recipient_id, actor_id, article_id, type, message, link, is_read, is_active) VALUES
(1, 2, 1, 'like', 'baikinman liked your article', '/articles/1', 0, 1),
(1, 3, 2, 'like', 'dokinchan liked your article', '/articles/2', 0, 1),
(2, 1, 3, 'like', 'anpanman liked your article', '/articles/3', 0, 1),
(2, 5, 4, 'like', 'currypanman liked your article', '/articles/4', 0, 1),
(3, 6, 5, 'like', 'melonpanna liked your article', '/articles/5', 0, 1),
(4, 8, 7, 'like', 'horrorman liked your article', '/articles/7', 0, 1),
(5, 10, 9, 'like', 'creampanda liked your article', '/articles/9', 0, 1),
(6, 12, 11, 'like', 'omusubiman liked your article', '/articles/11', 0, 1),
(7, 14, 13, 'like', 'butterko liked your article', '/articles/13', 0, 1),
(8, 1, 15, 'like', 'anpanman liked your article', '/articles/15', 0, 1);
